---
title: "Proposal"
---

# Birth Defects in Minnesota

Suweda Said, Yeshe Jangchup, Sam Kenney

## Description

This project will investigate different relationships between birth defects in Minnesota, as well as potential contributing factors to their prevalence, such as maternal features and folic acid. 

## Research questions

- How does pre- and post-fortification of folic acid impact the prevalence of neural tube defect?

- How does maternal education and financial background affect different birth defects?

- What patterns in birth defects can we observe across maternal age groups? Are certain conditions more or less commonly associated with certain age brackets?

## Motivations

Public health policies are constantly evolving and adapting to better support health outcomes. Birth defects have been a major focus of these policies. Especially with recent focus on maternal health policies, it's important to understand how these initiatives are actually affecting child outcomes. 

## Dataset

We will be using the [Minnesota Department of Health's datasets for birth defects](https://mndata.web.health.state.mn.us/birth_defects/messaging_pre.html).

## Teamwork

Our primary method of communication will be over text. 

Point of Contact: Suweda

Technical Lead: Sam

Style Lead: Yeshe

In case of conflicting opinions, we will do our best to compromise and incorporate elements of everyone's idea as possible. If this is not possible, or if we are struggling to meet individual deadlines, we will work together to create a plan that meets everyone's needs, and utilize outside resources and supports as necessary. 

## Implementation Plan

Following Milestone 4, we will meet and create a plan to build a cohesive and collaborative story. 

### Deliverables:

- README.md: one person will be responsible for preparing the README by 5/1

- Report: 

  - Motivation: 4/10
  
  - Research Questions: 4/15
  
  - Background: 4/17
  
  - Data: 4/20
  
  - Data Insights: 4/23
  
  - Conclusions: 4/27
  
  - Limitations/Future Work: 4/29
  
- Final presentation video: 5/4

- Final presentation slides: 5/3

